metric_groups:
  "1.ATTEMPTS TO GET ANSWERED":
    iQ1a: "Q1a. No. of attempts for connecting"
    iQ1b: "Q1b. Did receive a call after first attempt?"
  "2 CALL AGENT GREETING":
    iQ2b: "Q2b. Backgrpound Noise on Call"
    iQ2c: "Q2c. Was call agent polite and assisting?"
    iQ2d: "Q2d. Call Agent Attentiveness"
    iQ2e: "Q2e. Did Call Agent Personalize Interaction?"
    iQ2f: "Q2f. Call Agent's Manners"
    iQ2g: "Q2g. Clarity of Call Agent's communication"
    iQ2h: "Q2h. Did Call Agent asked relevant information?"
    iQ2i_1: "Q2i. Did Call Agent give right information?"
    iQ2i_2: "Q2j. Did Call Agent Confirms Appointment?"
    iQ2k_1: "Q2k. Did Call Agent asked if appointment date is fine?"
    iQ2l: "Q2l. Did customer get a confirmation on appointment?"
    iQ2m: "Q2m. Average time spent on call?"

  "3 OVERALL IMPRESSION":
    iQ5e: "Q5e. Overall Experience "

weight_variables:
  "1.ATTEMPTS TO GET ANSWERED": wGREETING
  "2 CALL AGENT GREETING": wAGENTGREETING
  "3 OVERALL IMPRESSION": wIMPRESSION 